# Generated by Django 4.1.6 on 2023-02-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_remove_conversation_members_conversation_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-modified_at',)},
        ),
    ]
